# Generated by Django 3.0.7 on 2020-06-16 21:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=100)),
                ('Word_Count', models.TextField()),
                ('Trans_Count', models.TextField()),
                ('Emotion_Count', models.TextField()),
                ('Activity_Count', models.TextField()),
                ('Top5Word_Count', models.TextField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.TextField()),
                ('Trans_Type', models.CharField(max_length=100)),
                ('Area_Visited', models.CharField(max_length=100)),
                ('Emotion', models.CharField(max_length=50)),
                ('Activity', models.CharField(max_length=50)),
                ('Response_Date', models.DateField(auto_now_add=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
